# Generated by Django 5.2.12 on 2026-09-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(max_length=400)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('development', 'Development'), ('research', 'Research'), ('release', 'Release'), ('tutorial', 'Tutorial'), ('community', 'Community'), ('other', 'Other')], default='development', max_length=30)),
                ('tags', models.CharField(blank=True, help_text='Separate tags with commas.', max_length=300)),
                ('author', models.CharField(default='EmotionWeb Team', max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
