# Generated by Django 5.2.12 on 2026-09-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contributorprofile_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributorprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='contributorprofile',
            name='github_username',
        ),
    ]
